chore: merge develop into switch PR
KILTprotocol/kilt-node pull request #679
Opened 2024-07-29 12:54 UTC by Ad96el

Please start the review at the second commit:

This commit is the merge of develop into the switch pallet PR: 0897dd24f83bbbfb86fb91f6fcd1f42715207240
This commit contains all changes required to make the switch pallet compile and updates the XCM version to 4: 073f2d52d2c8fc512017a232a53b1a2dabc0e948

2024-07-29 14:04 UTC, ntn-x2 requested changes
I only focused on the switch pallet and the relevant logic in the runtime.

I tried to point out all places where we use `xcm::latest`, and make sure we use explicit versions, in this case v4. It's a bit like using the `latest` tag in Docker: could go right, but could go wrong if something changes in a new version, and we have no way to know. Hence switching to the new version should be a planned decision.

Other than that, there's few things with the test cases, but big big kudos for having the patience to change them. I'm thinking it might be time to introduce some macros to reduce the boilerplate by a lot.

But great job so far!

2024-07-30 08:02 UTC, Ad96el commented on pallets/pallet-asset-switch/src/xcm/transact/mock.rs
> +pub struct MockRuntimeHoldReaseon([u8; 4]);
I looked in the required trait bounds for RuntimeHoldReaseon. I guess there is more required. In addition, RuntimeHoldReason is requiring VariantCount which is not implemented in an array

2024-07-30 08:05 UTC, Ad96el commented on pallets/pallet-asset-switch/src/xcm/transact/mock.rs
> +	type RuntimeFreezeReason = ();
Ah yes sure. I was thinking we need a proper HoldReason. I removed it in d5968e9438b35d7a51e4dab1f81e286debe8e00b

2024-07-30 08:21 UTC, Ad96el commented on pallets/pallet-asset-switch/src/benchmarking.rs
> +		let default_reserve_location: Location = Location {
Yes. I either need to call an `.into()` or create a new Arc by `Arc::new` which is both not allowed

2024-07-30 08:51 UTC, Ad96el commented on pallets/pallet-asset-switch/src/xcm/trade/xcm_fee_asset/tests/buy_weight.rs
> +		let location_v3: xcm::v3::MultiLocation = location.try_into().unwrap();
Well, the `get_switch_pair_info_for_remote_location` requires a v4 location. Either I have to convert this way or convert it into a `VersionedLocation` and parse that after, or is there a smooth way to convert it directly?

2024-07-30 10:47 UTC, Ad96el commented on pallets/pallet-asset-switch/src/xcm/match/tests.rs
> +	let location_v3: xcm::v3::MultiLocation = location.try_into().unwrap();
No, why? I transformed the v2 location to a v3 location. I explained the comment further blow, why I did that.

2024-07-30 10:57 UTC, Ad96el commented
Yeah, well, it was a quite active design decision to change the specific xcm version to latest for the xcm structs and stay on v4 for the tests. The traits themselves are not versioned and use the latest as well. I thought that for future xcm upgrades, the unit tests and integration tests would reveal any breaking changes. I guess both approaches are fine, so I changed them to version 4. No need for further discussion.

I have addressed all requested changes. It is a bit hard to keep track of the comments, so I did not link the corresponding PR to each comment.

I kindly ask you to review the additional commits made after your last comment.

2024-07-30 11:50 UTC, ntn-x2 approved these changes

2024-07-30 11:55 UTC, merged